create database if not exists JPA_DB_01;
create database if not exists JPA_DB_02;
create database if not exists JPA_DB_03;
create database if not exists DB_LAB_04_TABLE_PER_HIERARCHY;
create database if not exists DB_LAB_04_TABLE_PER_CLASS;
create database if not exists DB_LAB_04_TABLE_PER_SUBCLASS;
create database if not exists JPA_DB_05;
create database if not exists JPA_DB_06;
create database if not exists JPA_DB_07;
